### ISSUE TITLE
Really just a question, why not part of image-builder

### ISSUE THREAD

**Issue by jadonk** [beagleboard/Latest-Images#19]
Sorry to waste the bandwidth/space for this one, but why isn't this issue set just part of the beagleboard/image-builder repo?

**Comment by RobertCNelson** [comment]
@jadonk , yeah there is no issue tracker:

![issue_tracker](https://user-images.githubusercontent.com/91469/77714970-5a655280-6fa8-11ea-8d22-92dd45240cb9.png)

weird right?
