### ISSUE TITLE
Can Not Start bone101 web page on BBB BeagleBoard.org Debian IoT Image 2020-03-26

### ISSUE THREAD

**Issue by kenmartin-unix** [beagleboard/Latest-Images#25]
I can start NodeRed on port 1880
and Cloud9 on port 3000.

What port is the main start page on?
I used to use simply 192.168.7.2.

I did notice the service name for
node red changed from node-red.service
to nodered.service.

Is the image missing some software for
the main page?

Thanks

**Comment by RobertCNelson** [comment]
bone101 is eol

The default web interface port (80) is proxy'ed to Cloud9, anything useful from bone101 that wasn't already in cloud 9 got moved here:

![bone101](https://user-images.githubusercontent.com/91469/78184032-7a749600-742e-11ea-9b7f-df7a2e688f6b.png)

Regards,

**Comment by kenmartin-unix** [comment]
Package EOL
