### ISSUE TITLE
bb-customizations fails on sudo apt upgrade. Debian 4-6-2020 image

### ISSUE THREAD

**Issue by kenmartin-unix** [beagleboard/Latest-Images#47]
Beaglebone Black running Debian 4-6-2020 IoT release

After sudo apt update
During sudo apt upgrade the following failed

E: Failed to fetch http://repos.rcn-ee.com/debian/pool/main/b/bb-customizations/bb-customizations_1.20200511.1-0~buster+20200511_all.deb  404  Not Found [IP: 45.33.2.10 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by RobertCNelson** [comment]
@kenmartin-unix try again... you did a apt update/upgrade right when i pushed an update.. ;)
