### ISSUE TITLE
Improve apt update speed

### ISSUE THREAD

**Issue by JoseGoncalves** [beagleboard/Latest-Images#71]
**Is your feature request related to a problem? Please describe.**
Updating Debian packages with `apt update` command is slow.

**Describe the solution you'd like**
Configure `apt` default behaviour to disable the usage of "diff" files, adding a file in `/etc/apt/apt.conf.d/` with the following content:
```
Acquire::PDiffs "false";
```

**Additional context**
* Information on `apt update` methodologies with relevant info for this issue on "6.2.1 - TIP Incremental updates":
  https://debian-handbook.info/browse/stable/sect.apt-get.html

* This `apt` configuration is also used in Raspberry Pi OS (based on Debian Buster).
   They have added a `50raspi` file with this content:
   ```
   # never use pdiffs. Current implementation is very slow on low-powered devices
   Acquire::PDiffs "0";

   # download up to 5 pdiffs:
   #Acquire::PDiffs::FileLimit "5";
   ```
   and a `99speedup` file with this content:
   ```
   APT::Install-Recommends 0;
   Acquire::PDiffs "false";
   Acquire::Languages "none"; 
   Acquire::CompressionTypes::Order { "gz"; "bz2"; }
   ```

**Comment by RobertCNelson** [comment]
Thanks @JoseGoncalves so we left the PDiff's enabled years ago to save download data... I think at this point, i agree let's disable it..

**Comment by RobertCNelson** [comment]
We have no-langues also enabled..

When did CompressionTypes::Order come out?/

We also enable...
```
Acquire::GzipIndexes "true"; APT::Compressor::xz::Cost "40";
```

**Comment by JoseGoncalves** [comment]
Hi @RobertCNelson. `0` and `false` both disable an `apt` feature, but I think it's more explicit to use the later (as indicated in the [Debian Handbook](https://debian-handbook.info/browse/stable/sect.apt-get.html)), because it's more explicit on the nature of that config variable (a boolean).
