### ISSUE TITLE
Externship: 

### ISSUE THREAD

**Issue by Kjsstprakash** [beagleboard/Latest-Images#85]
# [Github Externship](https://github-externships.github.io/externship/) Proposal

* Student ID: `github ID of student making proposal`
* Mentors: `github IDs of people involved with BeagleBoard.org you think might help you`
* Repository: https://github.com/`your username`/`forked repository` (add documentation with a github wiki on the same repo)

## Status

This project is currently just a proposal.

# Proposal
Please complete the requirements listed on the [GSoC ideas page](https://bbb.io/gsocideas) and fill out this template.

## About you

* IRC: `IRC nickname`
* School: `university attending`
* Country: `geographical location`
* Primary language (We have mentors who speak multiple languages): `language`
* Typical work hours (We have mentors in various time zones): `8AM-5PM US Eastern`
* Previous externship and open source experience: `links to some of your projects`

## About your project

Project name: My super cool project
Description

In 10-20 sentences, what are you making, for whom, why and with what technologies (programming languages, etc.)? (We are looking for open source SOFTWARE submissions.)

### Timeline

Provide a development timeline with a milestone week and any pre-work. (A realistic timeline is critical to our selection process.)
| Date   | Milestone |
| ------ | --------- |
| Mon DD | Start     |
| Mon DD | Week #1   |
| Mon DD | Week #n   |
| Mon DD | End       |

### Experience and approach

In 5-15 sentences, convince us you will be able to successfully complete your project in the timeline you have described.
Contingency

What will you do if you get stuck on your project and your mentor isn’t around?

### Benefit

If successfully completed, what will its impact be on the BeagleBoard.org community? Include quotes from BeagleBoard.org community members who can be found on http://beagleboard.org/discuss and http://bbb.io/gsocchat.
Misc

Please complete the requirements listed on the ideas page. Provide link to pull request.

## Suggestions

Is there anything else we should have asked you?

**Comment by jadonk** [comment]
Closed because it was just a test?
